const LOCAL_KEY="kingfx_trades",DELETED_KEY="kingfx_deleted_trades";
const byId=id=>document.getElementById(id);
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const result=t=>{const r=String(t.result||t.outcome||"").toLowerCase();if(r.includes("win"))return"win";if(r.includes("loss"))return"loss";if(r==="be"||r.includes("break"))return"be";return num(t.pnl)>0?"win":num(t.pnl)<0?"loss":"be"};
const dateOf=t=>new Date(t.date||t.created_at||0);
const money=v=>`${v>0?"+":""}${v<0?"-":""}$${Math.abs(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function localRows(){try{return JSON.parse(localStorage.getItem(LOCAL_KEY)||"[]")}catch{return[]}}
function deleted(){try{return new Set(JSON.parse(localStorage.getItem(DELETED_KEY)||"[]").map(String))}catch{return new Set}}
function signature(t){return`${t.import_id||t.local_id||t.id||""}|${t.date||t.created_at||""}|${t.pair||""}|${t.pnl??""}`.toLowerCase()}
function merge(...sources){const out=[],seen=new Set,removed=deleted();sources.flat().forEach(t=>{const key=signature(t);if(!key||seen.has(key)||removed.has(String(t.id))||removed.has(String(t.import_id)))return;seen.add(key);out.push(t)});return out}
function streaks(trades){const ordered=[...trades].filter(t=>["win","loss"].includes(result(t))).sort((a,b)=>dateOf(a)-dateOf(b));const runs={win:[],loss:[]};let type="",length=0;ordered.forEach(t=>{const r=result(t);if(r===type)length++;else{if(type)runs[type].push(length);type=r;length=1}});if(type)runs[type].push(length);return{type,current:length,longWin:Math.max(0,...runs.win),longLoss:Math.max(0,...runs.loss)}}
function animate(id,target,format=n=>Math.round(n)){const el=byId(id),start=performance.now(),duration=700;function frame(now){const p=Math.min((now-start)/duration,1),v=target*(1-Math.pow(1-p,3));el.textContent=format(v);if(p<1)requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function render(trades){const wins=trades.filter(t=>result(t)==="win"),losses=trades.filter(t=>result(t)==="loss"),bes=trades.filter(t=>result(t)==="be"),net=trades.reduce((s,t)=>s+num(t.pnl),0),grossWin=wins.reduce((s,t)=>s+Math.max(0,num(t.pnl)),0),grossLoss=Math.abs(losses.reduce((s,t)=>s+Math.min(0,num(t.pnl)),0)),wr=(wins.length+losses.length)?wins.length/(wins.length+losses.length)*100:0,pf=grossLoss?grossWin/grossLoss:grossWin?Infinity:0;
byId("ovNet").closest(".commandCard").classList.toggle("negativeCard",net<0);
animate("ovNet",net,n=>money(n));animate("ovWinRate",wr,n=>`${n.toFixed(1)}%`);animate("ovTrades",trades.length);animate("ovProfitFactor",Number.isFinite(pf)?pf:0,n=>Number.isFinite(pf)?n.toFixed(2):"∞");byId("ovWinNote").textContent=`${wins.length} wins / ${losses.length} losses`;byId("donutTotal").textContent=trades.length;byId("donutWins").textContent=wins.length;byId("donutLosses").textContent=losses.length;byId("donutBE").textContent=bes.length;const total=Math.max(trades.length,1),wp=wins.length/total*100,lp=losses.length/total*100;byId("resultDonut").style.background=`radial-gradient(circle,#0b1023 56%,transparent 58%),conic-gradient(#10b981 0 ${wp}%,#ef4444 ${wp}% ${wp+lp}%,#64748b ${wp+lp}% 100%)`;
const sorted=[...trades].sort((a,b)=>dateOf(b)-dateOf(a));byId("overviewTrades").innerHTML=`<div class="overviewTradeRow tableHead"><span>Date</span><span>Pair</span><span>Result</span><span>Risk</span><span>P&amp;L</span><span>R:R</span></div>`+(sorted.slice(0,6).map(t=>`<div class="overviewTradeRow"><span>${isNaN(dateOf(t))?"—":dateOf(t).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</span><strong>${esc(String(t.pair||"—").toUpperCase())}</strong><span><b class="resultBadge ${result(t)}">${result(t)}</b></span><span>$${num(t.risk).toLocaleString()}</span><strong class="${num(t.pnl)>=0?"profit":"loss"}">${money(num(t.pnl))}</strong><span>${esc(t.rr||"—")}</span></div>`).join("")||`<div class="chartEmpty static">No trades recorded yet.</div>`);
const st=streaks(trades),isLoss=st.type==="loss";byId("ovCurrentStreak").textContent=st.current;byId("ovLongestWin").textContent=st.longWin;byId("ovLongestLoss").textContent=st.longLoss;byId("ovStreakType").textContent=st.type?`Current ${st.type} streak`:"No active streak";byId("ovStreakTitle").textContent=st.type?`${st.current} consecutive ${st.type}${st.current===1?"":"s"}`:"Waiting for results";byId("ovStreakAdvice").textContent=isLoss&&st.current>=3?"Protect capital. Reduce risk and review execution before the next trade.":st.type==="win"&&st.current>=3?"Momentum is strong. Keep the same risk and process.":"Completed wins and losses power this analysis.";byId("momentumHero").className=`momentumHero ${st.type}`;byId("momentumRing").style.setProperty("--progress",`${Math.min(st.current*14,100)}%`);
const pairMap={};trades.forEach(t=>pairMap[t.pair||"Unknown"]=(pairMap[t.pair||"Unknown"]||0)+num(t.pnl));const pairs=Object.entries(pairMap).sort((a,b)=>b[1]-a[1]);byId("overviewInsights").innerHTML=`<div><span>Best pair</span><strong>${esc(pairs[0]?.[0]||"—")}</strong><small class="profit">${pairs[0]?money(pairs[0][1]):"No data"}</small></div><div><span>Average trade</span><strong>${money(trades.length?net/trades.length:0)}</strong><small>Net expectancy</small></div><div><span>Risk state</span><strong>${isLoss&&st.current>=3?"Reduce exposure":"Normal"}</strong><small>${isLoss&&st.current>=3?"Losing streak alert":"Within plan"}</small></div>`;drawChart(sorted.reverse())}
function drawChart(trades){const canvas=byId("overviewChart"),rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const vals=[0];trades.forEach(t=>vals.push(vals.at(-1)+num(t.pnl)));byId("overviewEmpty").style.display=trades.length?"none":"grid";if(!trades.length)return;const pad=24,min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,pts=vals.map((v,i)=>[pad+i/(vals.length-1)*(rect.width-pad*2),rect.height-pad-(v-min)/range*(rect.height-pad*2)]);ctx.strokeStyle="rgba(148,163,184,.1)";for(let i=0;i<5;i++){const y=pad+i*(rect.height-pad*2)/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(rect.width-pad,y);ctx.stroke()}const grad=ctx.createLinearGradient(0,0,0,rect.height);grad.addColorStop(0,"rgba(16,185,129,.25)");grad.addColorStop(1,"rgba(16,185,129,0)");ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.lineTo(pts.at(-1)[0],rect.height-pad);ctx.lineTo(pts[0][0],rect.height-pad);ctx.fillStyle=grad;ctx.fill();ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle="#10b981";ctx.lineWidth=2;ctx.stroke()}
async function init(){let remote=[];if(window.sb){try{const{data}=await window.sb.from("trades").select("*");remote=data||[]}catch{}}const trades=merge(remote,localRows(),window.KINGFX_IMPORTED_TRADES||[]);render(trades);addEventListener("resize",()=>drawChart([...trades].sort((a,b)=>dateOf(a)-dateOf(b))))}
const now=new Date;byId("todayLabel").textContent=now.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});byId("overviewClock").textContent=now.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});if(window.sb)init();else{addEventListener("kingfx:supabase-ready",init,{once:true});setTimeout(init,800)}
